vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
       mission_image:
           uri_prefix: '%mission_image%'
           upload_destination: '%kernel.project_dir%/public%mission_image%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false
       actualite_image:
           uri_prefix: '%actualite_image%'
           upload_destination: '%kernel.project_dir%/public%actualite_image%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false
       partenaire_image:
           uri_prefix: '%partenaire_image%'
           upload_destination: '%kernel.project_dir%/public%partenaire_image%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false
       user_image:
           uri_prefix: '%user_image%'
           upload_destination: '%kernel.project_dir%/public%user_image%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false
